version: '2.2'
services:
  web:
    container_name: secure_note
    build: ./secure_note
    links: 
     - mysql:mysql
    restart: always
    environment:
     - SECRET_KEY=oHhh_n0000OooooO___YoU_shOUldnt_kn0vv_mY_k3333yyyy
    depends_on:
     - mysql
    volumes: 
      - './secure_note/src:/app'
    ports:
     - "8000:8000"

  mysql:
    container_name: mysql
    image: mysql:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    hostname: mysqlserver
    environment:
      - MYSQL_ROOT_PASSWORD=r00t_psswd_1s__A_r4nd0m_strrrr
    expose:
      - "3306"
    volumes:
      - ./sql_dump/:/docker-entrypoint-initdb.d

