version: "3.6"
services:
    iz-vocabulary-api:
        build: ./api
        restart: unless-stopped
        volumes: 
            - './api/src:/app'
    iz-vocabulary:
        build: ./iz-vocabulary
        restart: unless-stopped
        ports:
            - 8000:80